redis-config:
  url: 127.0.0.1:6379
  db: 0
  password: Redis@1234
  rdb_path: ./dump.rdb

app-config:
  name: app-demo
  db_password: App@1234
  admin_user: admin
  admin_passowrd: admin
  plugin: default